-- ============================================================================
-- Defence-tech startups — batch 2 of the Crustdata "Defense Tech Market Map
-- Q4 2026" additions. 11 US scaleups (AI/software/EW + space), each web-verified
-- against its official site on 2026-10-11. Deduped (none present); parent us_dtech.
-- Idempotent. Run in Supabase, then sync. (True Anomaly, K2 Space, Apex already mapped.)
-- ============================================================================
insert into public.nodes (id,label,parent,kind,does,entry,tags,status,origin,evidence_status,last_verified_at,verified_by,source) values
 ('us_modernintelligence','Modern Intelligence','us_dtech','org',
  'US defence-AI company; its Sovereign software runs multi-domain targeting on uncrewed systems — detecting, classifying and tracking objects and feeding target data to TAK.',
  'modernintelligence.ai','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["ai","autonomy","c4isr"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','modernintelligence.ai'),
 ('us_defenseunicorns','Defense Unicorns','us_dtech','org',
  'US defence software company providing UDS, an airgap-native platform to package, deploy and manage software on military systems across cloud, edge and disconnected environments.',
  'defenseunicorns.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["software","cyber"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','defenseunicorns.com'),
 ('us_aalyria','Aalyria','us_dtech','org',
  'US networking company orchestrating resilient high-throughput connectivity across land, sea, air and space (Spacetime) with Tightbeam laser-communications terminals.',
  'aalyria.com','{"w":["startup"],"o":["contract"],"t":[5,8],"d":["comms","space","software"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','aalyria.com'),
 ('us_picogrid','Picogrid','us_dtech','org',
  'US company providing software and hardware that connect sensors, platforms and operators across domains for defence, space and public-safety missions.',
  'picogrid.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["c4isr","software","autonomy"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','picogrid.com'),
 ('us_nominal','Nominal','us_dtech','org',
  'US test-and-operations software company; its Core data platform and Connect edge platform run hardware test and telemetry applications.',
  'nominal.io','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["software","simulation"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','nominal.io'),
 ('us_gravitics','Gravitics','us_dtech','org',
  'US space-hardware company building orbital carriers for space mobility and missile defence, plus commercial space-station modules on a common 4-metre design.',
  'gravitics.com','{"w":["startup"],"o":["contract"],"t":[4,7],"d":["space"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','gravitics.com'),
 ('us_turionspace','Turion Space','us_dtech','org',
  'US space company building vehicles, mission software and payloads for tactical space, space domain awareness and in-space logistics.',
  'turionspace.com','{"w":["startup"],"o":["contract"],"t":[5,8],"d":["space","c4isr"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','turionspace.com'),
 ('us_muonspace','Muon Space','us_dtech','org',
  'US company providing end-to-end satellite-constellation design and operations for government, civil and commercial remote-sensing missions.',
  'muonspace.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["space","eoisr"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','muonspace.com'),
 ('us_slingshot','Slingshot Aerospace','us_dtech','org',
  'US space-operations company providing space situational awareness and decision support via its own sensor network, data fusion, simulation and AI.',
  'slingshot.space','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["space","c4isr"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','slingshot.space'),
 ('us_twosixtech','Two Six Technologies','us_dtech','org',
  'US national-security technology company providing cyber, electronic-warfare and secure tactical-network products (Sentr, Helix) plus reverse-engineering and high-assurance solutions.',
  'twosixtech.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["cyber","ew","software"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','twosixtech.com'),
 ('us_vulcanelements','Vulcan Elements','us_dtech','org',
  'US manufacturer of rare-earth permanent magnets for defence, space, robotics and industry, building domestic magnet production in North Carolina.',
  'vulcanelements.com','{"w":["startup"],"o":["contract"],"t":[4,8],"d":["materials","microelec"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','vulcanelements.com')
on conflict (id) do update set label=excluded.label,parent=excluded.parent,does=excluded.does,entry=excluded.entry,
  tags=excluded.tags,status='published',origin=excluded.origin,evidence_status=excluded.evidence_status,
  last_verified_at=excluded.last_verified_at,verified_by=excluded.verified_by,source=excluded.source;
