-- ============================================================================
-- Defence-tech startups — batch 1 of the Crustdata "Defense Tech Market Map
-- Q4 2026" additions.  16 US venture-backed scaleups, each web-verified against
-- its official site on 2026-10-11 (origin=curated, evidence_status=verified).
-- Deduped against the map (none already present); parent us_dtech (US defence-
-- tech scaleups), matching the existing tag convention (saronic/shieldai/etc.).
-- Idempotent. Run in Supabase, then sync.
-- ============================================================================
insert into public.nodes (id,label,parent,kind,does,entry,tags,status,origin,evidence_status,last_verified_at,verified_by,source) values
 ('us_elroyair','Elroy Air','us_dtech','org',
  'US developer of autonomous VTOL cargo aircraft (the Chaparral) and cargo pods for expeditionary logistics and resupply.',
  'elroyair.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["air","autonomy","logistics"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','elroyair.com'),
 ('us_aevex','AEVEX Aerospace','us_dtech','org',
  'US provider of full-spectrum ISR, uncrewed systems and navigation/autonomy for US and allied forces.',
  'aevex.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["air","autonomy","c4isr"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','aevex.com'),
 ('us_overlandai','Overland AI','us_dtech','org',
  'US ground-autonomy company; its OverDrive stack and OverWatch system let one operator command a force of uncrewed ground vehicles.',
  'overland.ai','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["land","autonomy","software"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','overland.ai'),
 ('us_seasats','Seasats','us_dtech','org',
  'US maker of small, long-endurance autonomous surface vessels (Lightfish/Quickfish) for maritime ISR, interception and inspection.',
  'seasats.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["maritime","autonomy"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','seasats.com'),
 ('us_hiddenlevel','Hidden Level','us_dtech','org',
  'US passive RF-sensing company providing airspace awareness and counter-UAS detection across air, ground, sea and space.',
  'hiddenlevel.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["c4isr","counteruas","ew"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','hiddenlevel.com'),
 ('us_xbowsystems','X-Bow Systems','us_dtech','org',
  'US manufacturer of solid rocket motors using advanced/additive methods, with modular launch platforms and flight-test services.',
  'xbowsystems.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["weapons","materials","energy"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','xbowsystems.com'),
 ('us_shift5','Shift5','us_dtech','org',
  'US operational-technology cybersecurity firm analysing onboard serial-bus and RF data from military platforms for threat detection and predictive maintenance.',
  'shift5.io','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["cyber","software"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','shift5.io'),
 ('us_stokespace','Stoke Space','us_dtech','org',
  'US launch company developing Nova, a fully reusable rocket for low-cost access to and from any orbit.',
  'stokespace.com','{"w":["startup"],"o":["contract"],"t":[5,8],"d":["space"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','stokespace.com'),
 ('us_albedo','Albedo','us_dtech','org',
  'US operator of very-low-Earth-orbit satellites delivering very-high-resolution optical and thermal imagery and active sensing.',
  'albedo.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["space","eoisr"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','albedo.com'),
 ('us_onebrief','Onebrief','us_dtech','org',
  'US military command-and-planning platform combining operational data, agentic AI, collaborative planning and continuous wargaming.',
  'onebrief.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["software","c4isr","wargaming"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','onebrief.com'),
 ('us_qusecure','QuSecure','us_dtech','org',
  'US post-quantum cybersecurity firm providing crypto-agility software that migrates networks to quantum-resistant encryption without code changes.',
  'qusecure.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["cyber","quantum"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','qusecure.com'),
 ('us_relativityspace','Relativity Space','us_dtech','org',
  'US launch company building largely 3D-printed, reusable rockets (Terran R) for medium-to-heavy payloads.',
  'relativityspace.com','{"w":["startup"],"o":["contract"],"t":[5,8],"d":["space","materials"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','relativityspace.com'),
 ('us_varda','Varda Space Industries','us_dtech','org',
  'US in-space manufacturing company producing materials in microgravity and returning them via re-entry capsules; also offers hypersonic re-entry test services.',
  'varda.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["space","materials"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','varda.com'),
 ('us_impulsespace','Impulse Space','us_dtech','org',
  'US in-space mobility company building orbital transfer vehicles (Mira, Helios) that move payloads between orbits.',
  'impulsespace.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["space"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','impulsespace.com'),
 ('us_vast','Vast','us_dtech','org',
  'US company developing commercial space stations and orbital infrastructure (Haven-1).',
  'vastspace.com','{"w":["startup"],"o":["contract"],"t":[5,8],"d":["space"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','vastspace.com'),
 ('us_leolabs','LeoLabs','us_dtech','org',
  'US space-domain-awareness company tracking objects in low Earth orbit via a global radar network and cloud platform.',
  'leolabs.space','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["space","c4isr"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','leolabs.space')
on conflict (id) do update set label=excluded.label,parent=excluded.parent,does=excluded.does,entry=excluded.entry,
  tags=excluded.tags,status='published',origin=excluded.origin,evidence_status=excluded.evidence_status,
  last_verified_at=excluded.last_verified_at,verified_by=excluded.verified_by,source=excluded.source;
