-- ============================================================================
-- Defence-tech startups — batch 3 of the Crustdata "Defense Tech Market Map
-- Q4 2026" additions. 10 US (us_dtech) + 1 Israeli (D-Fend, pt_il), each web-
-- verified against its official site on 2026-10-11 (several had moved domains,
-- captured here). Deduped. Idempotent. Run in Supabase, then sync.
-- ============================================================================
insert into public.nodes (id,label,parent,kind,does,entry,tags,status,origin,evidence_status,last_verified_at,verified_by,source) values
 ('us_auterion','Auterion','us_dtech','org',
  'US/European autonomy company; its drone operating system, swarm software, launch systems and fleet-management tools run uncrewed systems for defence.',
  'auterion.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["autonomy","software","air"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','auterion.com'),
 ('us_darkhive','Darkhive','us_dtech','org',
  'US company building small, secure autonomous drones and the open software to operate them at scale for defence and public safety.',
  'darkhive.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["autonomy","air","software"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','darkhive.com'),
 ('us_thayermahan','ThayerMahan','us_dtech','org',
  'US maritime company providing autonomous passive-acoustic undersea surveillance and ocean-intelligence systems and services.',
  'thayermahan.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["maritime","c4isr"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','thayermahan.com'),
 ('us_terradepth','Terradepth','us_dtech','org',
  'US ocean-data company providing seafloor mapping via long-range autonomous underwater vehicles and its Absolute Ocean platform.',
  'terradepth.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["maritime","autonomy","software"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','terradepth.com'),
 ('us_fortemtech','Fortem Technologies','us_dtech','org',
  'US counter-drone company making detection radars and autonomous interceptor drones to detect and neutralise hostile UAS.',
  'fortemtech.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["counteruas","c4isr","autonomy"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','fortemtech.com'),
 ('us_firehawk','Firehawk','us_dtech','org',
  'US propulsion company developing 3D-printed hybrid rocket motors for defence and space applications.',
  'firehawkdefense.com','{"w":["startup"],"o":["contract"],"t":[5,8],"d":["weapons","energy","materials"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','firehawkdefense.com'),
 ('us_parrylabs','Parry Labs','us_dtech','org',
  'US defence-technology company providing modular open-systems hardware, software and autonomy so military platforms can interoperate in the field.',
  'parrylabs.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["software","c4isr","autonomy"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','parrylabs.com'),
 ('us_havocai','Havoc AI','us_dtech','org',
  'US autonomy-software company enabling one operator to command large numbers of uncrewed vehicles across sea, air and land.',
  'havocai.com','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["autonomy","maritime","software"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','havocai.com'),
 ('us_vatn','Vatn Systems','us_dtech','org',
  'US company mass-producing low-cost autonomous underwater vehicles for maritime defence.',
  'vatn.com','{"w":["startup"],"o":["contract"],"t":[5,8],"d":["maritime","autonomy"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','vatn.com'),
 ('us_neros','Neros','us_dtech','org',
  'US drone company building Archer FPV attack drones and the Crossbow ground-control station for the US and allies.',
  'neros.tech','{"w":["startup"],"o":["contract"],"t":[6,9],"d":["air","autonomy","weapons"],"a":"open","g":"us"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','neros.tech'),
 ('il_dfend','D-Fend Solutions','pt_il','org',
  'Israeli counter-drone company; its EnforceAir system uses RF cyber-takeover to detect and safely land rogue drones.',
  'd-fendsolutions.com','{"w":["startup"],"o":["contract"],"t":[7,9],"d":["counteruas","cyber","c4isr"],"a":"open","g":"il"}'::jsonb,
  'published','curated','verified','2026-10-11','maintainer','d-fendsolutions.com')
on conflict (id) do update set label=excluded.label,parent=excluded.parent,does=excluded.does,entry=excluded.entry,
  tags=excluded.tags,status='published',origin=excluded.origin,evidence_status=excluded.evidence_status,
  last_verified_at=excluded.last_verified_at,verified_by=excluded.verified_by,source=excluded.source;
